- name: update apt {{ letsencrypt_email }}
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600

- name: Install certbot
  package:
    name: ['certbot','python-certbot-nginx']
    state: present
