- name: create credentials folder if it does not already exist
  file:
    path: credentials
    state: directory
  become: yes

- name: ansible host - clean config.js
  local_action:
    module: file
    state: absent
    path: timemap/config.js
  become: no

- name: put config in timemap, replacing SERVER_ROOT with production URL
  local_action: "shell cat {{ timemap.config }} | gawk \"/SERVER_ROOT/ { print \\\"SERVER_ROOT: 'http{{ 's' if use_https else '' }}://{{ domain_name }}/{{timemap.name}}-server',\\\"; next; } /.*/ { print $1 }\" > timemap/config.js"
  become: no

- name: replace title in index.html
  local_action: "shell pwd && cat timemap/index.html | gawk \"/<title>.*/ { print \\\"<title>{{ timemap.display_name }}</title>\\\"; next; } /.*/ { print $1; }\" > timemap/index2.html && rm timemap/index.html && mv timemap/index2.html timemap/index.html"
  become: no

- name: ansible host - build app
  local_action:
    module: shell
    _raw_params: CI=false npm run build
    chdir: timemap
  become: no

- name: set publish directory
  set_fact: publish_dir={{ static_files_folder|default('/var/www/html') }}/{{ timemap.name }}
  when: "{{ not lookup('env', 'TIMEMAP_PUBLISH_AT_ROOT') }}"

- name: set publish directory
  set_fact: publish_dir={{ static_files_folder|default('/var/www/html') }}
  when: "{{ lookup('env', 'TIMEMAP_PUBLISH_AT_ROOT') }}"

- name: create root folder if it does not already exist
  file:
    path: "{{ static_files_folder }}"
    state: directory
  become: yes

- name: server - remove previous frontend if exists
  file:
    state: absent
    path: "{{ publish_dir }}"
  become: yes

- name: copy files from timemap build to server's static files folder
  copy:
    src: timemap/build/
    dest: "{{ publish_dir }}"
  become: yes

- name: copy config.js to credentials folder
  copy:
    src: timemap/config.js
    dest: credentials/{{ timemap.name }}_config.js
  become: yes


